apply plugin: 'org.springframework.boot'

dependencies {
    implementation project(':common')
    implementation project(':domain')
    implementation project(':infra')
    implementation project(':kafka')
    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'org.springframework.boot:spring-boot-starter-aop'
    implementation 'io.github.resilience4j:resilience4j-spring-boot3:2.2.0'
    runtimeOnly 'org.postgresql:postgresql'

    testImplementation 'org.mockito:mockito-core'
}