spring:
  application:
    name: stagepass-api
  profiles:
    active: local

server:
  port: 8080

toss:
  secret-key: test_sk_Z1aOwX7K8mO7ZY67Jb7jVyQxzvNP
  client-key: test_ck_24xLea5zVAzgR5DkmqJbrQAMYNwW