apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "stagepass.fullname" . }}-config
  labels:
    {{- include "stagepass.labels" . | nindent 4 }}
data:
  DB_URL: {{ .Values.config.dbUrl | quote }}
  DB_USERNAME: {{ .Values.config.dbUsername | quote }}
  REDIS_HOST: {{ .Values.config.redisHost | quote }}
  REDIS_PORT: {{ .Values.config.redisPort | quote }}
  KAFKA_BOOTSTRAP_SERVERS: {{ .Values.config.kafkaBootstrapServers | quote }}
  KAFKA_CONSUMER_GROUP: {{ .Values.config.kafkaConsumerGroup | quote }}
  CORS_ALLOWED_ORIGINS: {{ .Values.config.corsAllowedOrigins | quote }}
