apiVersion: v1
kind: Service
metadata:
  name: {{ include "stagepass.fullname" . }}
  labels:
    {{- include "stagepass.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "stagepass.apiSelectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
